import type { 
  TCTeamMember, 
  Lead, 
  Deal, 
  AidaInsight, 
  Vendor 
} from './tc-types'

export const tcTeamMembers: TCTeamMember[] = [
  { id: 'tc-1', name: 'Adrian Montenegro', initials: 'AM', activeCount: 15 },
  { id: 'tc-2', name: 'Transaction Coordinator #2', initials: 'TC', activeCount: 19 },
]

export const leads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Winslow Jones',
    location: 'Sapphire, NC',
    city: 'Sapphire',
    state: 'NC',
    stage: 'analyze_qualify',
    daysInStage: 4,
    docsReceived: 8,
    docsRequired: 15,
    tcId: 'tc-1',
    tcName: 'Adrian Montenegro',
    flags: ['Title Pre-Check requested, awaiting response (2 days)'],
    revenuePotential: 35400,
    healthScore: 62,
  },
  {
    id: 'lead-2',
    name: 'Robert Sawyer Johnson',
    location: 'Willow Spring, NC',
    city: 'Willow Spring',
    state: 'NC',
    stage: 'analyze_qualify',
    daysInStage: 7,
    docsReceived: 11,
    docsRequired: 15,
    tcId: 'tc-2',
    tcName: 'Transaction Coordinator #2',
    flags: ['Loan Quote pending', 'ID Verification not started'],
    revenuePotential: 12000,
    healthScore: 55,
  },
  {
    id: 'lead-3',
    name: 'Marcy Fox',
    location: 'Indianapolis, IN',
    city: 'Indianapolis',
    state: 'IN',
    stage: 'analyze_qualify',
    daysInStage: 2,
    docsReceived: 13,
    docsRequired: 15,
    tcId: 'tc-1',
    tcName: 'Adrian Montenegro',
    flags: ['House Canary report not downloaded'],
    revenuePotential: 80700,
    healthScore: 85,
  },
  {
    id: 'lead-4',
    name: 'Celeste Massey',
    location: 'Austin, TX',
    city: 'Austin',
    state: 'TX',
    stage: 'title_remediation',
    daysInStage: 6,
    docsReceived: 10,
    docsRequired: 15,
    tcId: 'tc-1',
    tcName: 'Adrian Montenegro',
    flags: [],
    revenuePotential: 28900,
    healthScore: 45,
    issueDescription: 'HOA rental restriction found',
  },
  {
    id: 'lead-5',
    name: 'Dennis Pruitt',
    location: 'Phoenix, AZ',
    city: 'Phoenix',
    state: 'AZ',
    stage: 'title_remediation',
    daysInStage: 11,
    docsReceived: 12,
    docsRequired: 15,
    tcId: 'tc-2',
    tcName: 'Transaction Coordinator #2',
    flags: [],
    revenuePotential: 41200,
    healthScore: 32,
    issueDescription: 'Lien discovered — $8,400 unpaid HOA dues',
  },
]

export const deals: Deal[] = [
  {
    id: 'deal-1',
    name: 'Stephen A Krizman',
    location: 'Denver, CO',
    city: 'Denver',
    state: 'CO',
    stage: 'closing',
    closingDate: new Date('2026-05-05'),
    revenue: 9798,
    healthScore: 82,
    tcId: 'tc-1',
    tcName: 'Adrian Montenegro',
    missingDocs: 0,
    lastContact: 'Title Co',
    lastContactDays: 1,
    milestonesComplete: 16,
    milestonesTotal: 16,
    closingProbability: 95,
    partnerName: 'Truehold Title',
  },
  {
    id: 'deal-2',
    name: 'Timothy Cline',
    location: 'Nashville, TN',
    city: 'Nashville',
    state: 'TN',
    stage: 'deals_title_remediation',
    closingDate: new Date('2026-05-15'),
    revenue: 18900,
    healthScore: 31,
    tcId: 'tc-2',
    tcName: 'Transaction Coordinator #2',
    missingDocs: 3,
    lastContact: 'Lender',
    lastContactDays: 5,
    milestonesComplete: 8,
    milestonesTotal: 16,
    blockerDescription: 'Lender unresponsive (5 days)',
    closingProbability: 50,
    partnerName: 'Truehold Title',
  },
  {
    id: 'deal-3',
    name: 'Clayton Lewis',
    location: 'Tampa, FL',
    city: 'Tampa',
    state: 'FL',
    stage: 'clear_to_close',
    closingDate: new Date('2026-05-15'),
    revenue: 12600,
    healthScore: 74,
    tcId: 'tc-1',
    tcName: 'Adrian Montenegro',
    missingDocs: 1,
    lastContact: 'Inspector',
    lastContactDays: 2,
    milestonesComplete: 14,
    milestonesTotal: 16,
    blockerDescription: 'Waiting: Inspection report final version',
    closingProbability: 75,
    partnerName: 'Truehold Title',
  },
  {
    id: 'deal-4',
    name: 'Jeff Locke',
    location: 'Seattle, WA',
    city: 'Seattle',
    state: 'WA',
    stage: 'inspection_scheduled',
    closingDate: new Date('2026-05-20'),
    revenue: 20800,
    healthScore: 45,
    tcId: 'tc-1',
    tcName: 'Adrian Montenegro',
    missingDocs: 2,
    lastContact: 'Title Co',
    lastContactDays: 7,
    milestonesComplete: 6,
    milestonesTotal: 16,
    blockerDescription: "Title co hasn't responded to payoff request (7 days)",
    closingProbability: 25,
    partnerName: 'Pacific Northwest Title',
  },
  {
    id: 'deal-5',
    name: 'Dean J Nance',
    location: 'Atlanta, GA',
    city: 'Atlanta',
    state: 'GA',
    stage: 'loan_processing',
    closingDate: new Date('2026-05-20'),
    revenue: 7500,
    healthScore: 61,
    tcId: 'tc-2',
    tcName: 'Transaction Coordinator #2',
    missingDocs: 1,
    lastContact: 'Lender',
    lastContactDays: 3,
    milestonesComplete: 10,
    milestonesTotal: 16,
    blockerDescription: 'Waiting: Final loan commitment letter',
    closingProbability: 25,
    partnerName: 'Velocity Mortgage',
  },
  {
    id: 'deal-6',
    name: 'Sonja Dixson',
    location: 'Charlotte, NC',
    city: 'Charlotte',
    state: 'NC',
    stage: 'closing_scheduled',
    closingDate: new Date('2026-05-26'),
    revenue: 8631,
    healthScore: 78,
    tcId: 'tc-1',
    tcName: 'Adrian Montenegro',
    missingDocs: 0,
    lastContact: 'Seller',
    lastContactDays: 1,
    milestonesComplete: 15,
    milestonesTotal: 16,
    closingProbability: 75,
    partnerName: 'Truehold Title',
  },
  {
    id: 'deal-7',
    name: 'Marc Franzese',
    location: 'Houston, TX',
    city: 'Houston',
    state: 'TX',
    stage: 'contract_assigned',
    closingDate: new Date('2026-06-17'),
    revenue: 29520,
    healthScore: 55,
    tcId: 'tc-1',
    tcName: 'Adrian Montenegro',
    missingDocs: 4,
    lastContact: 'N/A',
    lastContactDays: 0,
    milestonesComplete: 2,
    milestonesTotal: 16,
    blockerDescription: 'Just assigned — initial doc requests not yet sent',
    closingProbability: 50,
    partnerName: 'First American Title',
  },
  {
    id: 'deal-8',
    name: 'Ethan Medina',
    location: 'Las Vegas, NV',
    city: 'Las Vegas',
    state: 'NV',
    stage: 'loan_processing',
    closingDate: new Date('2026-06-21'),
    revenue: 24339,
    healthScore: 67,
    tcId: 'tc-2',
    tcName: 'Transaction Coordinator #2',
    missingDocs: 1,
    lastContact: 'HOA',
    lastContactDays: 4,
    milestonesComplete: 11,
    milestonesTotal: 16,
    blockerDescription: 'Waiting: Updated HOA docs',
    closingProbability: 60,
    partnerName: 'First American Title',
  },
  {
    id: 'deal-9',
    name: 'April R Maxfield',
    location: 'Portland, OR',
    city: 'Portland',
    state: 'OR',
    stage: 'inspection_scheduled',
    closingDate: new Date('2026-06-09'),
    revenue: 7500,
    healthScore: 72,
    tcId: 'tc-1',
    tcName: 'Adrian Montenegro',
    missingDocs: 2,
    lastContact: 'Inspector',
    lastContactDays: 2,
    milestonesComplete: 7,
    milestonesTotal: 16,
    blockerDescription: 'Inspector confirmed, awaiting report',
    closingProbability: 65,
    partnerName: 'Pacific Northwest Title',
  },
  {
    id: 'deal-10',
    name: 'Tonia Yvette Slocumb',
    location: 'Memphis, TN',
    city: 'Memphis',
    state: 'TN',
    stage: 'clear_to_close',
    closingDate: new Date('2026-06-24'),
    revenue: 18000,
    healthScore: 80,
    tcId: 'tc-1',
    tcName: 'Adrian Montenegro',
    missingDocs: 0,
    lastContact: 'Title Co',
    lastContactDays: 1,
    milestonesComplete: 15,
    milestonesTotal: 16,
    blockerDescription: 'Final walkthrough pending',
    closingProbability: 80,
    partnerName: 'Truehold Title',
  },
]

export const aidaInsights: AidaInsight[] = [
  {
    id: 'insight-1',
    severity: 'urgent',
    title: 'Timothy Cline — 3 Overdue Items',
    description: 'Closing in 12 days. Lender unresponsive for 5 days. Title commitment, Loan payoffs, and ID verification still missing.',
    entityType: 'deal',
    entityId: 'deal-2',
    entityName: 'Timothy Cline',
    primaryAction: { label: 'Draft Follow-up to Lender', type: 'draft_email' },
    secondaryAction: { label: 'View Deal', type: 'view_detail' },
  },
  {
    id: 'insight-2',
    severity: 'warning',
    title: 'Dennis Pruitt — Title Issue Found',
    description: 'HOA lien of $8,400 discovered in Title Pre-Check. AIDA identified 3 similar cases resolved in 8-12 days via direct HOA negotiation.',
    entityType: 'lead',
    entityId: 'lead-5',
    entityName: 'Dennis Pruitt',
    primaryAction: { label: 'Draft HOA Negotiation Letter', type: 'draft_email' },
    secondaryAction: { label: 'View Lead', type: 'view_detail' },
  },
  {
    id: 'insight-3',
    severity: 'success',
    title: 'Stephen A Krizman — All Clear to Close',
    description: 'All 16 milestones complete. Closing confirmed for May 5. Revenue: $9,798. No action needed.',
    entityType: 'deal',
    entityId: 'deal-1',
    entityName: 'Stephen A Krizman',
    primaryAction: { label: 'View Closing Details', type: 'view_detail' },
  },
]

export const vendors: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'Truehold Title',
    type: 'title_company',
    states: ['FL', 'GA', 'SC', 'NC', 'TN'],
    contactName: 'Maria Santos',
    contactEmail: 'maria@trueholdtitle.com',
    contactPhone: '(813) 555-0142',
    avgTurnaround: '3-4 days',
    rating: 4.8,
    notes: 'Excellent response times, preferred partner',
  },
  {
    id: 'vendor-2',
    name: 'First American Title',
    type: 'title_company',
    states: ['All'],
    contactName: 'Derek Olsen',
    contactEmail: 'dolsen@firstam.com',
    contactPhone: '(800) 555-0301',
    avgTurnaround: '5-7 days',
    rating: 4.2,
  },
  {
    id: 'vendor-3',
    name: 'Pacific Northwest Title',
    type: 'title_company',
    states: ['WA', 'OR', 'ID'],
    contactName: 'Lisa Chen',
    contactEmail: 'lchen@pnwtitle.com',
    contactPhone: '(206) 555-0198',
    avgTurnaround: '4-5 days',
    rating: 4.6,
  },
  {
    id: 'vendor-4',
    name: 'Velocity Mortgage',
    type: 'lender',
    states: ['FL', 'TX', 'GA', 'NC', 'TN'],
    contactName: 'James Ruiz',
    contactEmail: 'jruiz@velocitymtg.com',
    contactPhone: '(855) 555-0212',
    avgTurnaround: '48hrs for commitment',
    rating: 4.5,
  },
  {
    id: 'vendor-5',
    name: 'CrossCountry Mortgage',
    type: 'lender',
    states: ['All'],
    contactName: 'Amy Park',
    contactEmail: 'apark@ccmortgage.com',
    contactPhone: '(888) 555-0345',
    avgTurnaround: '72hrs',
    rating: 4.1,
  },
  {
    id: 'vendor-6',
    name: 'Elite Property Inspections',
    type: 'inspector',
    states: ['FL', 'GA'],
    contactName: 'Bob Martinez',
    contactEmail: 'bob@eliteinspect.com',
    contactPhone: '(407) 555-0167',
    avgTurnaround: 'Same week',
    rating: 4.9,
    notes: 'Top-rated inspector, always thorough',
  },
  {
    id: 'vendor-7',
    name: 'Northwest Home Inspectors',
    type: 'inspector',
    states: ['WA', 'OR'],
    contactName: 'Tom Nguyen',
    contactEmail: 'tnguyen@nwhome.com',
    contactPhone: '(503) 555-0234',
    avgTurnaround: '2-3 days',
    rating: 4.4,
  },
]

// Helper function to get stage display name
export function getStageName(stage: string): string {
  const stageNames: Record<string, string> = {
    analyze_qualify: 'Analyze & Qualify',
    title_remediation: 'Title Remediation',
    contract_assigned: 'Contract Assigned',
    inspection_scheduled: 'Inspection Scheduled',
    loan_processing: 'Loan Processing',
    clear_to_close: 'Clear to Close',
    closing_scheduled: 'Closing Scheduled',
    deals_title_remediation: 'Title Remediation',
    closing: 'Closing',
  }
  return stageNames[stage] || stage
}

// Helper function to get vendor type display name
export function getVendorTypeName(type: string): string {
  const typeNames: Record<string, string> = {
    title_company: 'Title Company',
    lender: 'Lender',
    inspector: 'Home Inspector',
    hoa_management: 'HOA Management',
    attorney: 'Real Estate Attorney',
  }
  return typeNames[type] || type
}

// Helper to format currency
export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

// Helper to get days until closing
export function getDaysUntilClosing(closingDate: Date): number {
  const now = new Date()
  const diffTime = closingDate.getTime() - now.getTime()
  return Math.ceil(diffTime / (1000 * 60 * 60 * 24))
}
